spring.application.name=backend

server.servlet.context-path=/api

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:postgresql://localhost:5432/property_app
spring.datasource.username=rearck
spring.datasource.password=Ayush@8279
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update